/**
 * Fetch wrapper that automatically retries with .json extension for static export.
 * When running on GitHub Pages (static export), API routes like /api/overview
 * will return 404. This wrapper detects that and automatically tries /api/overview.json
 * which is a static file generated by scripts/generate-static-api.mjs.
 *
 * In local/development mode (Next.js dev server with API routes), the first
 * request to /api/overview will succeed and no fallback is needed.
 *
 * URLs with query parameters are handled by inserting .json before the query
 * string: /api/reviews?page=1 → /api/reviews.json?page=1
 */

const originalFetch = globalThis.fetch;

export async function wrappedFetch(input: RequestInfo | URL, init?: RequestInit): Promise<Response> {
  const response = await originalFetch(input, init);

  if (!response.ok && response.status === 404) {
    const urlStr =
      typeof input === "string"
        ? input
        : input instanceof URL
        ? input.toString()
        : (input as Request).url;

    // Only try fallback for /api/ paths (not /api/x/export or /api/x.json)
    if (urlStr.startsWith("/api/") && !urlStr.endsWith(".json")) {
      const [basePath, queryString] =
        urlStr.includes("?") ? urlStr.split("?") : [urlStr, ""];
      const jsonUrl = queryString
        ? `${basePath}.json?${queryString}`
        : `${basePath}.json`;
      return originalFetch(jsonUrl, init);
    }
  }

  return response;
}

// Apply the wrapper at app startup
if (typeof window !== "undefined") {
  globalThis.fetch = wrappedFetch;
}

export default wrappedFetch;
